name: Auto Pull from DriveHQ and Commit

on:
  workflow_dispatch:  # allows manual trigger
  schedule:
    - cron: '*/30 * * * *'  # runs every 30 minutes

jobs:
  auto-pull:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Pull from SFTP
        env:
          SFTP_USER: ${{ secrets.SFTP_USER }}
          SFTP_PASS: ${{ secrets.SFTP_PASS }}
        run: |
          echo "set sftp:connect-program 'ssh -o StrictHostKeyChecking=no'" >> ~/.lftprc
          mkdir -p temp_download
          lftp -u $SFTP_USER,$SFTP_PASS sftp://ftp.drivehq.com <<EOF
          mirror --verbose /project/ temp_download/
          bye
          EOF
          chmod -R u+rw temp_download

      - name: Copy files into repo
        run: |
          cp -r temp_download/* .
          rm -rf temp_download

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git add .
          git commit -m "Auto-pulled from DriveHQ at $(date)" || echo "Nothing to commit"
          git push