name: Auto Pull from DriveHQ and Commit

on:
  workflow_dispatch:  # allows manual trigger
  schedule:
    - cron: '*/30 * * * *'  # runs every 30 minutes

jobs:
  auto-pull:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Pull from SFTP (DriveHQ)
        env:
          SFTP_USER: ${{ secrets.SFTP_USER }}
          SFTP_PASS: ${{ secrets.SFTP_PASS }}
        run: |
          mkdir -p temp_download
          sshpass -p "$SFTP_PASS" sftp -o StrictHostKeyChecking=no $SFTP_USER@ftp.drivehq.com <<EOF
          lcd temp_download
          cd /project/
          mget *
          bye
          EOF
          chmod -R u+rw temp_download

      - name: Copy files into repo
        run: |
          cp -r temp_download/* .
          rm -rf temp_download

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git add .
          git commit -m "Auto-pulled from DriveHQ at $(date)" || echo "Nothing to commit"
          git push